---
llamacpp_serving_active_profile: "{{ llm_gpu_active_profiles_by_engine.llama_cpp }}"
llamacpp_serving_profiles:
  medium-b:
    enabled: true
    engine: llama_cpp
    max_model_len: 32768
    max_num_seqs: 8
    flash_attention: true
    gpu_layers: 99
    port: '{{ nvidia_gpu_guest_api_port }}'
  16gb:
    enabled: true
    engine: llama_cpp
    max_model_len: 32768
    max_num_seqs: 1
    flash_attention: true
    gpu_layers: 99
    port: '{{ nvidia_gpu_guest_api_port }}'
  max:
    enabled: true
    engine: llama_cpp
    max_model_len: 131072
    max_num_seqs: 1
    flash_attention: true
    gpu_layers: 99
    extra_args:
      - -lm
      - mmap
      - -lzm
      - 'on'
    port: '{{ nvidia_gpu_guest_api_port }}'
  glm-flash:
    enabled: true
    engine: llama_cpp
    max_model_len: 8192
    max_num_seqs: 1
    flash_attention: true
    gpu_layers: 99
    port: '{{ nvidia_gpu_guest_api_port }}'
llamacpp_serving_engine: llama_cpp
