---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Wait for the container to accept connections
      ansible.builtin.wait_for_connection:
        timeout: 60

    - name: Gather facts
      ansible.builtin.setup:
