---
- name: Restart llm-cpu-scaler
  ansible.builtin.systemd:
    name: "{{ llm_cpu_scaler.service }}"
    state: restarted
    daemon_reload: true

- name: Restart llm-cpu-scaler timer
  ansible.builtin.systemd:
    name: "{{ llm_cpu_scaler.timer }}"
    state: restarted
    daemon_reload: true
