---
name: Copilot Setup Steps

on:
  workflow_call:

jobs:
  copilot-setup-steps:
    name: Copilot Setup Steps
    runs-on: ubuntu-latest
    timeout-minutes: >-
      ${{ (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.ref == 'develop' &&
      github.event.pull_request.head.repo.full_name == github.repository) && 60 || 10 }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install ansible tools
        run: pip install ansible-core ansible-lint
